server:
  port: 18002
eureka:
  instance:
    prefer-ip-address: true
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://localhost:18000/eureka/,http://localhost:18001/eureka/
spring:
  application:
    name: eureka-server2
