spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxqianger/config-file
          username: zhangxqianger@vip.qq.com
          password: 13053187a
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka

server:
  port: 19001
